#ifndef QUEUE_H
#define QUEUE_H

template <typename T>
class Queue {
public:                        // Don't change the public intergace
  Queue();
  Queue(const Queue<T>&);
  ~Queue();
  void enqueue(const T&);
  T dequeue();
  unsigned size() const;
  unsigned capacity() const;
  bool is_empty() const;
  bool resize_capacity(unsigned);
private:
  T* items;                    // You may want to change these
  unsigned front;              // although they provide sufficient
  unsigned num_items;          // infromation to construct a queue
  unsigned capacity_size;
};

/* You need to change all the functions below.  I put in enough details
   to ensure the code would compile.  It does work at the moment.  */

/* Constructor; should create an empty queue with capacity 8 */

template <typename T>
Queue<T>::Queue() {
	num_items = 8;
	front = 0;
	items = new T[num_items];
} // Initialise pointer T to the size of array 8

/* Copy Constructor: note that this is generated by default, but the default copy constructor does the wrong thing */

template <typename T>
Queue<T>::Queue(const Queue<T>& rhs) {
	front = rhs.front;
	num_items = rhs.num_items;
	items = new T[num_items];
	memcpy(items, rhs.items, num_items*sizeof(T));
}

/* Destructor needs to free up memory */

template <typename T>
Queue<T>::~Queue() {
	delete[] items;
}

/* enqueue: add item to the list.  This may need to resize the list (if you want you can create another function resize in the head file Queue.h). In the standard library this would be called push. */

template <typename T>
void Queue<T>::enqueue(const T& item) {
	num_items++;
	items[num_items] = item;
	if (num_items = capacity_size) {
		num_items *= 2;
		realloc(items, num_items*sizeof(T));
	}
}

/* dequeue: remove the first element in the queue and returns it (in the standard library top() would return the first element in the queuue but not remove it.  pop() would remove the first element in the queue, but not return anything).  This should throw std::out_of_range when the queue is empty */

template <typename T>
T Queue<T>::dequeue() {
	unsigned temp = items[front];
	items[front] = nullptr;
	front++;
	return temp; // T(-1);
}

/* size: returns the number of elements in the queue.  As this can't be negative we make this an unsigned integer.  The const in the definition tells us that this command does not change the Queue data structure */

template <typename T>
unsigned Queue<T>::size() const {return num_items;}

/* is_empty: returns true if queue is empty */

template <typename T>
bool Queue<T>::is_empty() const {return num_items == 0;}


/* capacity: tells up how much memory we have reserved */

template <typename T>
unsigned Queue<T>::capacity() const {return num_items*sizeof(T);}

/* resize_capacity: if the capacity request is at least as large as the number of elements the capacity should be modified and return true other leave the capacity unchanged and return false */

template <typename T>
bool Queue<T>::resize_capacity(unsigned capacity_request) {
	if (capacity_request >= num_items) {
		num_items *= 2;
		realloc(items, num_items*sizeof(T));
		return true;
	}
	return false;
}



#endif
